import { useEffect, useState } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import Navbar from '../components/Navbar'
import { getCampaignReport } from '../services/api'
import jsPDF from 'jspdf'

export default function Report() {
  const { campaignId } = useParams()
  const navigate = useNavigate()
  const [report, setReport] = useState(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    getCampaignReport(campaignId)
      .then(r => setReport(r.data))
      .catch(err => console.error(err))
      .finally(() => setLoading(false))
  }, [campaignId])

  const exportPDF = () => {
    if (!report) return
    const doc = new jsPDF()
    const { campaign, stats, transcripts } = report

    // Header
    doc.setFillColor(79, 70, 229)
    doc.rect(0, 0, 210, 35, 'F')
    doc.setTextColor(255, 255, 255)
    doc.setFontSize(20)
    doc.text('VoiceIQ — Campaign Report', 15, 15)
    doc.setFontSize(11)
    doc.text(`Campaign: ${campaign.name}`, 15, 25)
    doc.text(`Generated: ${new Date().toLocaleString()}`, 15, 32)

    // Reset color
    doc.setTextColor(0, 0, 0)
    let y = 50

    // Campaign info
    doc.setFontSize(13)
    doc.setFont(undefined, 'bold')
    doc.text('Campaign Details', 15, y)
    doc.setFont(undefined, 'normal')
    doc.setFontSize(10)
    y += 8
    doc.text(`Status: ${campaign.status}`, 15, y); y += 6
    doc.text(`Language: ${campaign.language || 'English'}`, 15, y); y += 6
    doc.text(`Created: ${new Date(campaign.created_at).toLocaleString()}`, 15, y); y += 6
    const scriptLines = doc.splitTextToSize(`Script: ${campaign.script}`, 180)
    doc.text(scriptLines, 15, y)
    y += scriptLines.length * 5 + 8

    // Stats
    doc.setFontSize(13)
    doc.setFont(undefined, 'bold')
    doc.text('Campaign Statistics', 15, y)
    doc.setFont(undefined, 'normal')
    doc.setFontSize(10)
    y += 8

    const statsData = [
      ['Total contacts', stats.total_contacts],
      ['Calls completed', stats.calls_completed],
      ['Calls pending', stats.calls_pending],
      ['Completion rate', `${stats.completion_rate}%`],
      ['Positive calls', stats.positive],
      ['Neutral calls', stats.neutral],
      ['Negative calls', stats.negative],
    ]

    statsData.forEach(([label, value]) => {
      doc.text(`• ${label}: ${value}`, 15, y)
      y += 6
    })

    y += 5

    // Sentiment bar
    doc.setFontSize(13)
    doc.setFont(undefined, 'bold')
    doc.text('Sentiment Breakdown', 15, y)
    y += 8

    const total = stats.calls_completed || 1
    const posW = Math.round((stats.positive / total) * 150)
    const neuW = Math.round((stats.neutral / total) * 150)
    const negW = Math.round((stats.negative / total) * 150)

    doc.setFillColor(16, 185, 129)
    doc.rect(15, y, posW, 8, 'F')
    doc.setFillColor(107, 114, 128)
    doc.rect(15 + posW, y, neuW, 8, 'F')
    doc.setFillColor(239, 68, 68)
    doc.rect(15 + posW + neuW, y, negW, 8, 'F')

    y += 12
    doc.setFontSize(9)
    doc.setFont(undefined, 'normal')
    doc.text(`■ Positive: ${stats.positive}   ■ Neutral: ${stats.neutral}   ■ Negative: ${stats.negative}`, 15, y)
    y += 12

    // Transcripts
    doc.setFontSize(13)
    doc.setFont(undefined, 'bold')
    doc.text('Call Summaries', 15, y)
    y += 8

    transcripts.forEach((t, i) => {
      if (y > 260) {
        doc.addPage()
        y = 20
      }
      doc.setFontSize(10)
      doc.setFont(undefined, 'bold')
      doc.text(`${i + 1}. ${t.contacts?.name || 'Unknown'} (${t.contacts?.phone || ''})`, 15, y)
      y += 6
      doc.setFont(undefined, 'normal')
      doc.setFontSize(9)
      doc.text(`Sentiment: ${t.sentiment} | Date: ${new Date(t.created_at).toLocaleString()}`, 15, y)
      y += 5
      const summaryLines = doc.splitTextToSize(`Summary: ${t.summary || 'No summary'}`, 180)
      doc.text(summaryLines, 15, y)
      y += summaryLines.length * 5 + 6
    })

    // Footer
    const pageCount = doc.internal.getNumberOfPages()
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i)
      doc.setFontSize(8)
      doc.setTextColor(150, 150, 150)
      doc.text(`VoiceIQ Report — Page ${i} of ${pageCount}`, 15, 290)
      doc.text('Generated by VoiceIQ AI Bulk Call Simulator', 110, 290)
    }

    doc.save(`VoiceIQ_Report_${campaign.name}_${new Date().toLocaleDateString()}.pdf`)
  }

  const sentimentColor = (s) => {
    if (s === 'positive') return 'text-green-600 bg-green-50'
    if (s === 'negative') return 'text-red-600 bg-red-50'
    return 'text-gray-600 bg-gray-50'
  }

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-50">
        <Navbar />
        <div className="flex items-center justify-center h-64">
          <p className="text-gray-400">Loading report...</p>
        </div>
      </div>
    )
  }

  if (!report) {
    return (
      <div className="min-h-screen bg-gray-50">
        <Navbar />
        <div className="flex items-center justify-center h-64">
          <p className="text-red-400">Failed to load report.</p>
        </div>
      </div>
    )
  }

  const { campaign, stats, transcripts } = report

  return (
    <div className="min-h-screen bg-gray-50">
      <Navbar />
      <div className="max-w-5xl mx-auto px-6 py-8">

        {/* Header */}
        <div className="flex items-start justify-between mb-6">
          <div>
            <button
              onClick={() => navigate('/campaigns')}
              className="text-sm text-gray-500 hover:text-gray-700 mb-2 block"
            >
              ← Back to campaigns
            </button>
            <h1 className="text-2xl font-semibold text-gray-800">{campaign.name}</h1>
            <p className="text-sm text-gray-500 mt-1">Campaign Report</p>
          </div>
          <button
            onClick={exportPDF}
            className="bg-indigo-600 text-white px-4 py-2 rounded-lg text-sm hover:bg-indigo-700 flex items-center gap-2"
          >
            📄 Export PDF Report
          </button>
        </div>

        {/* Stats grid */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
          {[
            { label: 'Total contacts', value: stats.total_contacts, color: 'text-gray-800' },
            { label: 'Calls completed', value: stats.calls_completed, color: 'text-indigo-600' },
            { label: 'Completion rate', value: `${stats.completion_rate}%`, color: 'text-green-600' },
            { label: 'Pending calls', value: stats.calls_pending, color: 'text-yellow-600' },
          ].map(s => (
            <div key={s.label} className="bg-white rounded-xl border border-gray-200 p-5">
              <p className={`text-3xl font-semibold ${s.color}`}>{s.value}</p>
              <p className="text-sm text-gray-500 mt-1">{s.label}</p>
            </div>
          ))}
        </div>

        {/* Sentiment breakdown */}
        <div className="bg-white rounded-xl border border-gray-200 p-6 mb-6">
          <h2 className="text-base font-medium text-gray-700 mb-4">Sentiment breakdown</h2>
          <div className="grid grid-cols-3 gap-4 mb-4">
            {[
              { label: 'Positive', value: stats.positive, color: 'bg-green-500', text: 'text-green-700', bg: 'bg-green-50' },
              { label: 'Neutral', value: stats.neutral, color: 'bg-gray-400', text: 'text-gray-700', bg: 'bg-gray-50' },
              { label: 'Negative', value: stats.negative, color: 'bg-red-500', text: 'text-red-700', bg: 'bg-red-50' },
            ].map(s => (
              <div key={s.label} className={`${s.bg} rounded-xl p-4 text-center`}>
                <p className={`text-2xl font-semibold ${s.text}`}>{s.value}</p>
                <p className={`text-sm ${s.text} mt-1`}>{s.label}</p>
              </div>
            ))}
          </div>

          {/* Visual bar */}
          <div className="flex rounded-full overflow-hidden h-4">
            {stats.calls_completed > 0 && (
              <>
                <div
                  className="bg-green-500 transition-all"
                  style={{ width: `${(stats.positive / stats.calls_completed) * 100}%` }}
                />
                <div
                  className="bg-gray-300 transition-all"
                  style={{ width: `${(stats.neutral / stats.calls_completed) * 100}%` }}
                />
                <div
                  className="bg-red-500 transition-all"
                  style={{ width: `${(stats.negative / stats.calls_completed) * 100}%` }}
                />
              </>
            )}
          </div>
          <div className="flex gap-4 mt-2 text-xs text-gray-500">
            <span>🟢 Positive</span>
            <span>⚪ Neutral</span>
            <span>🔴 Negative</span>
          </div>
        </div>

        {/* Campaign details */}
        <div className="bg-white rounded-xl border border-gray-200 p-6 mb-6">
          <h2 className="text-base font-medium text-gray-700 mb-3">Campaign details</h2>
          <div className="grid grid-cols-2 gap-4 text-sm">
            <div>
              <p className="text-gray-500">Status</p>
              <p className="font-medium text-gray-800 capitalize">{campaign.status}</p>
            </div>
            <div>
              <p className="text-gray-500">Language</p>
              <p className="font-medium text-gray-800">{campaign.language || 'English'}</p>
            </div>
            <div>
              <p className="text-gray-500">Created</p>
              <p className="font-medium text-gray-800">{new Date(campaign.created_at).toLocaleString()}</p>
            </div>
            <div>
              <p className="text-gray-500">Scheduled</p>
              <p className="font-medium text-gray-800">
                {campaign.scheduled_at ? new Date(campaign.scheduled_at).toLocaleString() : 'Not scheduled'}
              </p>
            </div>
          </div>
          <div className="mt-3">
            <p className="text-gray-500 text-sm mb-1">Script</p>
            <p className="text-sm text-gray-700 bg-gray-50 rounded-lg p-3">{campaign.script}</p>
          </div>
        </div>

        {/* Call summaries */}
        <div className="bg-white rounded-xl border border-gray-200 p-6">
          <h2 className="text-base font-medium text-gray-700 mb-4">
            Call summaries ({transcripts.length})
          </h2>

          {transcripts.length === 0 ? (
            <p className="text-sm text-gray-400 text-center py-8">
              No calls completed yet for this campaign
            </p>
          ) : (
            <div className="space-y-4">
              {transcripts.map((t, i) => (
                <div key={t.id} className="border border-gray-100 rounded-xl p-4 hover:border-gray-200">
                  <div className="flex items-start justify-between mb-2">
                    <div>
                      <p className="font-medium text-gray-800 text-sm">
                        {i + 1}. {t.contacts?.name || 'Unknown'}
                      </p>
                      <p className="text-xs text-gray-400">{t.contacts?.phone}</p>
                    </div>
                    <div className="text-right">
                      <span className={`inline-block px-2 py-0.5 rounded-full text-xs font-medium ${sentimentColor(t.sentiment)}`}>
                        {t.sentiment}
                      </span>
                      <p className="text-xs text-gray-400 mt-1">
                        {new Date(t.created_at).toLocaleString()}
                      </p>
                    </div>
                  </div>
                  {t.summary && (
                    <p className="text-sm text-gray-600 bg-gray-50 rounded-lg px-3 py-2">
                      {t.summary}
                    </p>
                  )}
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  )
}